// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: echo.proto

package echo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingMessage, error)
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error)
	ClientStreamEcho(ctx context.Context, opts ...grpc.CallOption) (Echo_ClientStreamEchoClient, error)
	ServerStreamEcho(ctx context.Context, in *CountMessage, opts ...grpc.CallOption) (Echo_ServerStreamEchoClient, error)
	BidiStreamEcho(ctx context.Context, opts ...grpc.CallOption) (Echo_BidiStreamEchoClient, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/echo.Echo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error) {
	out := new(EchoMessage)
	err := c.cc.Invoke(ctx, "/echo.Echo/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) ClientStreamEcho(ctx context.Context, opts ...grpc.CallOption) (Echo_ClientStreamEchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], "/echo.Echo/ClientStreamEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoClientStreamEchoClient{stream}
	return x, nil
}

type Echo_ClientStreamEchoClient interface {
	Send(*EchoMessage) error
	CloseAndRecv() (*CountMessage, error)
	grpc.ClientStream
}

type echoClientStreamEchoClient struct {
	grpc.ClientStream
}

func (x *echoClientStreamEchoClient) Send(m *EchoMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoClientStreamEchoClient) CloseAndRecv() (*CountMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CountMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) ServerStreamEcho(ctx context.Context, in *CountMessage, opts ...grpc.CallOption) (Echo_ServerStreamEchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], "/echo.Echo/ServerStreamEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServerStreamEchoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Echo_ServerStreamEchoClient interface {
	Recv() (*EchoMessage, error)
	grpc.ClientStream
}

type echoServerStreamEchoClient struct {
	grpc.ClientStream
}

func (x *echoServerStreamEchoClient) Recv() (*EchoMessage, error) {
	m := new(EchoMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoClient) BidiStreamEcho(ctx context.Context, opts ...grpc.CallOption) (Echo_BidiStreamEchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[2], "/echo.Echo/BidiStreamEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoBidiStreamEchoClient{stream}
	return x, nil
}

type Echo_BidiStreamEchoClient interface {
	Send(*EchoMessage) error
	Recv() (*EchoMessage, error)
	grpc.ClientStream
}

type echoBidiStreamEchoClient struct {
	grpc.ClientStream
}

func (x *echoBidiStreamEchoClient) Send(m *EchoMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoBidiStreamEchoClient) Recv() (*EchoMessage, error) {
	m := new(EchoMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	Ping(context.Context, *emptypb.Empty) (*PingMessage, error)
	Echo(context.Context, *EchoMessage) (*EchoMessage, error)
	ClientStreamEcho(Echo_ClientStreamEchoServer) error
	ServerStreamEcho(*CountMessage, Echo_ServerStreamEchoServer) error
	BidiStreamEcho(Echo_BidiStreamEchoServer) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) Ping(context.Context, *emptypb.Empty) (*PingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEchoServer) Echo(context.Context, *EchoMessage) (*EchoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoServer) ClientStreamEcho(Echo_ClientStreamEchoServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamEcho not implemented")
}
func (UnimplementedEchoServer) ServerStreamEcho(*CountMessage, Echo_ServerStreamEchoServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamEcho not implemented")
}
func (UnimplementedEchoServer) BidiStreamEcho(Echo_BidiStreamEchoServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStreamEcho not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echo/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_ClientStreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).ClientStreamEcho(&echoClientStreamEchoServer{stream})
}

type Echo_ClientStreamEchoServer interface {
	SendAndClose(*CountMessage) error
	Recv() (*EchoMessage, error)
	grpc.ServerStream
}

type echoClientStreamEchoServer struct {
	grpc.ServerStream
}

func (x *echoClientStreamEchoServer) SendAndClose(m *CountMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoClientStreamEchoServer) Recv() (*EchoMessage, error) {
	m := new(EchoMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Echo_ServerStreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).ServerStreamEcho(m, &echoServerStreamEchoServer{stream})
}

type Echo_ServerStreamEchoServer interface {
	Send(*EchoMessage) error
	grpc.ServerStream
}

type echoServerStreamEchoServer struct {
	grpc.ServerStream
}

func (x *echoServerStreamEchoServer) Send(m *EchoMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Echo_BidiStreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).BidiStreamEcho(&echoBidiStreamEchoServer{stream})
}

type Echo_BidiStreamEchoServer interface {
	Send(*EchoMessage) error
	Recv() (*EchoMessage, error)
	grpc.ServerStream
}

type echoBidiStreamEchoServer struct {
	grpc.ServerStream
}

func (x *echoBidiStreamEchoServer) Send(m *EchoMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoBidiStreamEchoServer) Recv() (*EchoMessage, error) {
	m := new(EchoMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Echo_Ping_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreamEcho",
			Handler:       _Echo_ClientStreamEcho_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamEcho",
			Handler:       _Echo_ServerStreamEcho_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStreamEcho",
			Handler:       _Echo_BidiStreamEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "echo.proto",
}
